on: workflow_dispatch

name: TEST

jobs:
  scan:
    runs-on: ubuntu-22.04-arm
    steps: 
      - name: Run scan
        run: docker run --platform linux/amd64 --rm -v /var/run/docker.sock:/var/run/docker.sock aikidosecurity/local-scanner image-scan xxx --apikey xxx
